-- 0000_better_auth_core.sql
-- better-auth core tables (user/session/account/verification) including the
-- `admin` and `phoneNumber` plugin columns and indexes.
-- Matching better-auth v1.7.5 postgres mapping: string->text, boolean->boolean,
-- date->timestamptz, id/text primary key (ids are generated by the app).

CREATE TABLE IF NOT EXISTS "user" (
  "id"                 text PRIMARY KEY NOT NULL,
  "name"               text NOT NULL,
  "email"              text NOT NULL,
  "emailVerified"      boolean NOT NULL DEFAULT false,
  "image"              text,
  "createdAt"          timestamptz NOT NULL,
  "updatedAt"          timestamptz NOT NULL,
  "phoneNumber"        text,
  "phoneNumberVerified" boolean,
  "role"               text DEFAULT 'user',
  "banned"             boolean NOT NULL DEFAULT false,
  "banReason"          text,
  "banExpires"         timestamptz
);

CREATE INDEX IF NOT EXISTS "user_email_idx"          ON "user" (email);
CREATE UNIQUE INDEX IF NOT EXISTS "user_email_unique"        ON "user" (email);
CREATE UNIQUE INDEX IF NOT EXISTS "user_phoneNumber_unique"  ON "user" ("phoneNumber");

CREATE TABLE IF NOT EXISTS "session" (
  "id"            text PRIMARY KEY NOT NULL,
  "expiresAt"     timestamptz NOT NULL,
  "token"         text NOT NULL,
  "createdAt"     timestamptz NOT NULL,
  "updatedAt"     timestamptz NOT NULL,
  "ipAddress"     text,
  "userAgent"     text,
  "userId"        text NOT NULL,
  "impersonatedBy" text,
  CONSTRAINT "session_userId_fk" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "session_token_unique" ON "session" (token);
CREATE INDEX IF NOT EXISTS "session_userId_idx"          ON "session" ("userId");

CREATE TABLE IF NOT EXISTS "account" (
  "id"                    text PRIMARY KEY NOT NULL,
  "accountId"             text NOT NULL,
  "providerId"            text NOT NULL,
  "userId"                text NOT NULL,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope"                 text,
  "password"              text,
  "createdAt"             timestamptz NOT NULL,
  "updatedAt"             timestamptz NOT NULL,
  CONSTRAINT "account_userId_fk" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");

CREATE TABLE IF NOT EXISTS "verification" (
  "id"          text PRIMARY KEY NOT NULL,
  "identifier"  text NOT NULL,
  "value"       text NOT NULL,
  "expiresAt"   timestamptz NOT NULL,
  "createdAt"   timestamptz NOT NULL,
  "updatedAt"   timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" (identifier);