import type { IconType } from 'react-icons'
import {
  MdAdjust,
  MdBook,
  MdDirectionsCar,
  MdExtension,
  MdFavorite,
  MdFlashOn,
  MdGridOn,
  MdGroup,
  MdHistory,
  MdHome,
  MdLanguage,
  MdLightbulb,
  MdMap,
  MdNewReleases,
  MdSettings,
  MdSportsSoccer,
  MdStyle,
  MdTouchApp,
  MdUpdate,
  MdVideogameAsset,
  MdWhatshot,
} from 'react-icons/md'

/**
 * Client-safe category metadata: labels, colors and icons only.
 * IMPORTANT: this module must never import `lib/games` / `data/games.json`,
 * otherwise the full catalog re-enters the client bundle.
 */

/** Serializable category shape passed from the server layout to client nav. */
export type NavCategory = {
  slug: string
  labelAr: string
  count: number
}

export const FALLBACK_STYLE: { icon: IconType; gradient: string } = {
  icon: MdVideogameAsset,
  gradient: 'from-violet-500 to-cyan-400',
}

const CATEGORY_STYLE: Record<string, { icon: IconType; gradient: string }> = {
  io: { icon: MdLanguage, gradient: 'from-fuchsia-500 to-violet-500' },
  action: { icon: MdFlashOn, gradient: 'from-rose-500 to-amber-400' },
  adventure: { icon: MdMap, gradient: 'from-purple-500 to-indigo-900' },
  arcade: { icon: MdVideogameAsset, gradient: 'from-violet-500 to-cyan-400' },
  beauty: { icon: MdFavorite, gradient: 'from-pink-400 to-rose-500' },
  'dress-up': { icon: MdFavorite, gradient: 'from-pink-400 to-rose-500' },
  girls: { icon: MdFavorite, gradient: 'from-pink-400 to-rose-500' },
  board: { icon: MdGridOn, gradient: 'from-stone-400 to-stone-700' },
  mahjong: { icon: MdGridOn, gradient: 'from-stone-400 to-stone-700' },
  card: { icon: MdStyle, gradient: 'from-indigo-400 to-purple-600' },
  cards: { icon: MdStyle, gradient: 'from-indigo-400 to-purple-600' },
  clicker: { icon: MdTouchApp, gradient: 'from-lime-400 to-emerald-600' },
  idle: { icon: MdTouchApp, gradient: 'from-lime-400 to-emerald-600' },
  driving: { icon: MdDirectionsCar, gradient: 'from-sky-400 to-indigo-600' },
  car: { icon: MdDirectionsCar, gradient: 'from-sky-400 to-indigo-600' },
  racing: { icon: MdDirectionsCar, gradient: 'from-sky-400 to-indigo-600' },
  moto: { icon: MdDirectionsCar, gradient: 'from-sky-400 to-indigo-600' },
  parking: { icon: MdDirectionsCar, gradient: 'from-sky-400 to-indigo-600' },
  puzzle: { icon: MdExtension, gradient: 'from-amber-400 to-rose-400' },
  merge: { icon: MdExtension, gradient: 'from-amber-400 to-rose-400' },
  brain: { icon: MdLightbulb, gradient: 'from-amber-300 to-orange-500' },
  shooting: { icon: MdAdjust, gradient: 'from-slate-500 to-slate-800' },
  sniper: { icon: MdAdjust, gradient: 'from-slate-500 to-slate-800' },
  zombie: { icon: MdAdjust, gradient: 'from-green-600 to-emerald-900' },
  simulation: { icon: MdSettings, gradient: 'from-teal-400 to-emerald-700' },
  cooking: { icon: MdSettings, gradient: 'from-orange-300 to-amber-600' },
  sports: { icon: MdSportsSoccer, gradient: 'from-emerald-400 to-sky-500' },
  soccer: { icon: MdSportsSoccer, gradient: 'from-emerald-400 to-sky-500' },
  football: { icon: MdSportsSoccer, gradient: 'from-emerald-400 to-sky-500' },
  basketball: { icon: MdSportsSoccer, gradient: 'from-emerald-400 to-sky-500' },
  tennis: { icon: MdSportsSoccer, gradient: 'from-emerald-400 to-sky-500' },
  pool: { icon: MdSportsSoccer, gradient: 'from-emerald-400 to-sky-500' },
  strategy: { icon: MdLightbulb, gradient: 'from-orange-400 to-red-600' },
  'tower-defense': { icon: MdLightbulb, gradient: 'from-orange-400 to-red-600' },
  trivia: { icon: MdBook, gradient: 'from-teal-400 to-blue-600' },
  word: { icon: MdBook, gradient: 'from-yellow-300 to-amber-600' },
  escape: { icon: MdMap, gradient: 'from-teal-500 to-emerald-800' },
  platform: { icon: MdVideogameAsset, gradient: 'from-sky-400 to-blue-700' },
  stickman: { icon: MdFlashOn, gradient: 'from-zinc-500 to-zinc-800' },
  multiplayer: { icon: MdGroup, gradient: 'from-indigo-500 to-cyan-400' },
  'two-player': { icon: MdGroup, gradient: 'from-indigo-500 to-cyan-400' },
  skill: { icon: MdExtension, gradient: 'from-cyan-400 to-blue-600' },
  flash: { icon: MdFlashOn, gradient: 'from-yellow-300 to-orange-500' },
  fighting: { icon: MdFlashOn, gradient: 'from-red-500 to-orange-500' },
  decoration: { icon: MdStyle, gradient: 'from-purple-300 to-pink-400' },
  new: { icon: MdLightbulb, gradient: 'from-emerald-300 to-teal-500' },
  animals: { icon: MdFavorite, gradient: 'from-green-300 to-emerald-500' },
  farm: { icon: MdSettings, gradient: 'from-lime-400 to-emerald-600' },
  restaurant: { icon: MdSettings, gradient: 'from-orange-300 to-amber-600' },
}

export function categoryStyle(slug: string): { icon: IconType; gradient: string } {
  return CATEGORY_STYLE[slug] ?? FALLBACK_STYLE
}

const AR_LABELS: Record<string, string> = {
  sports: 'رياضية',
  racing: 'سباقات',
  brain: 'ذكاء',
  puzzle: 'بازل',
  arcade: 'أركيد',
  multiplayer: 'جماعية',
  action: 'أكشن',
  'two-player': 'لاعبان',
  car: 'سيارات',
  driving: 'قيادة',
  simulation: 'محاكاة',
  watermelon: 'بطيخ',
  'american-football': 'كرة أمريكية',
  platform: 'منصات',
  skill: 'مهارة',
  easy: 'سهلة',
  soccer: 'كرة القدم',
  war: 'حروب',
  strategy: 'استراتيجية',
  new: 'جديدة',
  shooting: 'تصويب',
  adventure: 'مغامرات',
  cards: 'ورق',
  card: 'ورق',
  fighting: 'قتال',
  obby: 'أوبي',
  'dress-up': 'تلبيس',
  beauty: 'تجميل',
  idle: 'تراكمية',
  color: 'تلوين',
  decoration: 'ديكور',
  flash: 'فلاش',
  educational: 'تعليمية',
  running: 'جري',
  board: 'لوحية',
  scary: 'رعب',
  survival: 'بقاء',
  basketball: 'سلة',
  tractor: 'جرارات',
  girls: 'بنات',
  matching: 'مطابقة',
  merge: 'دمج',
  zombie: 'زومبي',
  blocks: 'مكعبات',
  gun: 'أسلحة',
  slime: 'سلايم',
  ball: 'كرة',
  number: 'أرقام',
  bowling: 'بولينج',
  clicker: 'نقر',
  brainrot: 'برين روت',
  drawing: 'رسم',
  'bubble-shooter': 'فقاعات',
  airplane: 'طائرات',
  farm: 'مزرعة',
  animals: 'حيوانات',
  restaurant: 'مطاعم',
  nitrome: 'نيتروم',
  bike: 'دراجات',
  boat: 'قوارب',
  pizza: 'بيتزا',
  cats: 'قطط',
  chess: 'شطرنج',
  monster: 'وحوش',
  cooking: 'طبخ',
  cricket: 'كريكيت',
  'tower-defense': 'دفاع الأبراج',
  io: 'آي أو',
  tycoon: 'إدارة',
  dinosaur: 'ديناصورات',
  hair: 'تصفيف الشعر',
  'make-up': 'مكياج',
  doctor: 'طبيب',
  escape: 'هروب',
  stickman: 'ستيك مان',
  'hidden-object': 'أشياء مخفية',
  fishing: 'صيد',
  quiz: 'اختبارات',
  'battle-royale': 'باتل رويال',
  parkour: 'باركور',
  '3d': 'ثلاثية الأبعاد',
  words: 'كلمات',
  ragdoll: 'دمى',
  sniper: 'قناصة',
  typing: 'كتابة',
  robot: 'روبوتات',
  food: 'طعام',
  monkey: 'قرود',
  parking: 'ركن',
  space: 'فضاء',
  pool: 'بلياردو',
  boxing: 'ملاكمة',
  retro: 'كلاسيكية',
  construction: 'بناء',
  mahjong: 'ماجونج',
  snake: 'ثعبان',
  music: 'موسيقى',
  'co-op': 'تعاونية',
  'match-3': 'مطابقة 3',
  sudoku: 'سودوكو',
  tanks: 'دبابات',
  wrestling: 'مصارعة',
  difficult: 'صعبة',
}

export function categoryLabelAr(slug: string, fallback?: string): string {
  return AR_LABELS[slug] ?? fallback ?? slug
}

export const SIDEBAR_TOP: { label: string; href: string; icon: IconType; disabled?: boolean }[] = [
  { label: 'الرئيسية', href: '/', icon: MdHome },
  { label: 'لُعبت مؤخرًا', href: '', icon: MdHistory, disabled: true },
  { label: 'جديد', href: '/games/?sort=new', icon: MdNewReleases },
  { label: 'ألعاب رائجة', href: '/games/?sort=hot', icon: MdWhatshot },
  { label: 'محدّثة', href: '/games/?sort=updated', icon: MdUpdate },
]
